package internal

import (
	"strconv"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/suite"
)

type goLangTypesGenerator struct {
	suite.Suite
}

// Make sure that VariableThatShouldStartAtFive is set to five
// before each test
func (suite *goLangTypesGenerator) SetupTest() {
}

// All methods that begin with "Test" are run as tests within a
// suite.
func (s *goLangTypesGenerator) TestEmptyGoTemplate() {
	result, err := GenerateGoTypes([]PromptSchema{}, &ConfigurationOutputGo{
		Prefix:      "PP",
		PackageName: "yj",
		Output:      "./example/types.g.go",
	})
	assert.Nil(s.T(), err)
	str := string(result)
	assert.Equal(s.T(), len(result), 0)

	assert.Empty(s.T(), str)
}
func (s *goLangTypesGenerator) TestSchemaGoTemplate() {
	ps := []PromptSchema{}
	for i := 0; i < 10; i++ {
		idx := strconv.Itoa(i)
		variables := []PromptVariable{}

		for j := 0; j < i; j++ {
			jid := strconv.Itoa(j)
			variables = append(variables, PromptVariable{
				Name: "var" + jid,
				Type: "string",
			})
		}
		ps = append(ps, PromptSchema{
			Name:        "test" + idx,
			HashID:      "hashid" + idx,
			Description: "test description " + idx,
			Variables:   variables,
			TokenCount:  100 + i,
			CreatedAt:   time.Date(2022, 1, 1, 0, 0, 0, 0, time.UTC),
		})
	}

	result, err := GenerateGoTypes(ps, &ConfigurationOutputGo{
		Prefix:      "PP",
		PackageName: "yj",
		Output:      "./example/types.g.go",
	})
	assert.Nil(s.T(), err)
	str := string(result)

	assert.Greater(s.T(), len(result), 0)

	assert.NotEmpty(s.T(), str)
	assert.Contains(s.T(), str, "package yj")
	assert.Contains(s.T(), str, "// generated by PromptPal cli. PLEASE DO NOT EDIT")
	assert.Contains(s.T(), str, "PPPromptTest0 PPPrompts = \"hashid0\"")
	assert.Contains(s.T(), str, "PPPromptTest9 PPPrompts = \"hashid9\"")
}

func TestGoLangTypesGeneratorTestSuite(t *testing.T) {
	suite.Run(t, new(goLangTypesGenerator))
}
