// generated by PromptPal cli. PLEASE DO NOT EDIT
package {{ .PackageName }}
type {{ .Prefix }}Prompts string

const (
	{{ range .Prompts }}
	{{ $.Prefix }}Prompt{{ capitalize .Name }} {{ $.Prefix }}Prompts = "{{ .HashID }}"
	{{ end }}
)

{{ range .Prompts }}
type {{ $.Prefix }}Prompt{{ capitalize .Name}}Variables struct {
	{{ range $v := .Variables }}
	{{ capitalize $v.Name }} string `json:"{{ $v.Name }}"`
	{{ end}}
}
{{ end }}


